services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tranfer_db
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
